name: ci-build-test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: .NET Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./Frosty.sln

      - name: Build
        run: dotnet build ./Frosty.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Frosty.sln --configuration Release --no-build --verbosity normal

  frontend:
    name: Frontend Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/clientapp-react
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/clientapp-react/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Upload FE artifact
        uses: actions/upload-artifact@v4
        with:
          name: fe-dist
          path: src/clientapp-react/dist
          if-no-files-found: error
