name: Test AWS OIDC Role

on:
  workflow_dispatch:  # lets you trigger it manually from Actions tab

permissions:
  id-token: write     # required for OIDC
  contents: read

env:
  AWS_REGION: eu-central-1
  ROLE_TO_ASSUME: arn:aws:iam::457518023943:role/github-deploy

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test credentials
        run: aws sts get-caller-identity
